mod ai;
mod image_hosting;
mod pdf_export;
mod update;

use base64::Engine as _;
use reqwest::header::{CONTENT_TYPE, USER_AGENT};
use std::collections::{BTreeMap, HashMap};
use std::ffi::{OsStr, OsString};
use std::path::{Path, PathBuf};
use std::sync::Mutex;
use tauri::{
    Emitter, LogicalPosition, LogicalSize, Manager, Position, Size, WebviewBuilder, WebviewUrl,
};
use tauri_plugin_fs::FsExt;

const MAX_REMOTE_IMAGE_BYTES: usize = 12 * 1024 * 1024;
const MAX_LOCAL_IMAGE_BYTES: usize = 24 * 1024 * 1024;
const PREVIEW_IMAGE_USER_AGENT: &str = "No.1 Markdown Editor Preview Image Loader";
const SINGLE_INSTANCE_OPEN_FILES_EVENT: &str = "single-instance-open-files";

struct PendingOpenPaths(Mutex<Vec<String>>);

/// Content-script bridge injected into every external browser webview.
const BROWSER_BRIDGE_SCRIPT: &str = include_str!("browser_bridge.js");

/// Title-channel reassembly buffers, keyed by requestId. Used as the
/// cross-platform fallback when the external webview cannot reach the Tauri IPC
/// (`browser_report_content`) directly — the bridge then streams the base64
/// payload through `document.title` in chunks.
#[derive(Default)]
struct BrowserTitleChannels(Mutex<HashMap<String, TitleChannelBuffer>>);

struct TitleChannelBuffer {
    total: usize,
    chunks: BTreeMap<usize, String>,
}

/// Payload emitted to the frontend on `browser-agent-data-{label}` once a full
/// page snapshot has been received (via either channel). `payload` is the JSON
/// string produced by the bridge's `buildSnapshot()`.
#[derive(Clone, serde::Serialize)]
#[serde(rename_all = "camelCase")]
struct BrowserAgentData {
    request_id: String,
    payload: String,
}

/// requestIds are generated by the frontend and embedded into an `eval` string;
/// restrict them to an alphanumeric allow-list so they can never break out of
/// the script literal or the title-channel delimiter scheme.
fn is_safe_request_id(request_id: &str) -> bool {
    !request_id.is_empty()
        && request_id.len() <= 64
        && request_id.bytes().all(|b| b.is_ascii_alphanumeric())
}

/// Reassemble base64 chunks streamed through `document.title` and, once
/// complete, decode and emit them to the frontend. No-op for titles that don't
/// carry the agent marker (i.e. ordinary page title changes).
fn handle_browser_title_report<R: tauri::Runtime>(
    app: &tauri::AppHandle<R>,
    label: &str,
    title: &str,
) {
    const MARKER: &str = "__AGENT__";
    let Some(rest) = title.strip_prefix(MARKER) else {
        return;
    };
    // rest = <requestId>|<seq>|<total>|<base64 chunk>
    let mut parts = rest.splitn(4, '|');
    let (Some(request_id), Some(seq), Some(total), Some(chunk)) =
        (parts.next(), parts.next(), parts.next(), parts.next())
    else {
        return;
    };
    let (Ok(seq), Ok(total)) = (seq.parse::<usize>(), total.parse::<usize>()) else {
        return;
    };
    if total == 0 || seq >= total || !is_safe_request_id(request_id) {
        return;
    }

    let state = app.state::<BrowserTitleChannels>();
    let Ok(mut map) = state.0.lock() else {
        return;
    };
    let buffer = map
        .entry(request_id.to_string())
        .or_insert_with(|| TitleChannelBuffer {
            total,
            chunks: BTreeMap::new(),
        });
    buffer.total = total;
    buffer.chunks.insert(seq, chunk.to_string());
    if buffer.chunks.len() < buffer.total {
        return;
    }

    let assembled: String = buffer.chunks.values().cloned().collect();
    map.remove(request_id);
    drop(map);

    let Ok(bytes) = base64::engine::general_purpose::STANDARD.decode(assembled.as_bytes()) else {
        return;
    };
    let Ok(payload) = String::from_utf8(bytes) else {
        return;
    };

    let _ = app.emit(
        &format!("browser-agent-data-{}", label),
        BrowserAgentData {
            request_id: request_id.to_string(),
            payload,
        },
    );
}

/// Primary report channel: the bridge invokes this directly from the external
/// webview. We resolve the originating webview's label and forward the snapshot
/// to the frontend on the same `browser-agent-data-{label}` event the title
/// channel uses, so the frontend has a single listener regardless of channel.
///
/// Currently unreachable by default: external browser webviews have no
/// capability granting them this command, so the bridge falls back to the
/// `document.title` channel (see `handle_browser_title_report`). Kept registered
/// for a future opt-in fast path behind a tightly-scoped capability.
#[allow(dead_code)]
#[tauri::command]
fn browser_report_content<R: tauri::Runtime>(
    webview: tauri::Webview<R>,
    app: tauri::AppHandle<R>,
    request_id: String,
    payload: String,
) -> Result<(), String> {
    if !is_safe_request_id(&request_id) {
        return Err("Invalid request id".to_string());
    }
    let label = webview.label().to_string();
    app.emit(
        &format!("browser-agent-data-{}", label),
        BrowserAgentData { request_id, payload },
    )
    .map_err(|error| error.to_string())
}

/// Trigger snapshot collection in a browser webview by calling the injected
/// `window.__agentCollect(requestId)`. The result arrives asynchronously on
/// `browser-agent-data-{label}` (see the two report channels above).
#[tauri::command]
async fn browser_collect_content<R: tauri::Runtime>(
    app: tauri::AppHandle<R>,
    label: String,
    request_id: String,
) -> Result<(), String> {
    if !is_safe_request_id(&request_id) {
        return Err("Invalid request id".to_string());
    }
    if let Some(webview) = app.get_webview(&label) {
        let (tx, rx) = tokio::sync::oneshot::channel();
        let _ = app.run_on_main_thread(move || {
            let script = format!(
                "window.__agentCollect && window.__agentCollect('{}')",
                request_id
            );
            let res = webview.eval(&script).map_err(|error| error.to_string());
            let _ = tx.send(res);
        });
        rx.await.map_err(|e| format!("Channel error: {e}"))?
    } else {
        Err(format!("Browser webview not found: {label}"))
    }
}

#[tauri::command]
async fn read_file(path: String) -> Result<String, String> {
    tokio::task::spawn_blocking(move || std::fs::read_to_string(path))
        .await
        .map_err(|error| format!("Failed to join file read task: {error}"))?
        .map_err(|error| error.to_string())
}

#[tauri::command]
fn write_file(path: String, content: String) -> Result<(), String> {
    ensure_parent_directory(&path)?;
    std::fs::write(&path, content).map_err(|e| e.to_string())
}

#[tauri::command]
fn write_binary_file(path: String, bytes: Vec<u8>) -> Result<(), String> {
    ensure_parent_directory(&path)?;
    std::fs::write(&path, bytes).map_err(|e| e.to_string())
}

#[tauri::command]
fn copy_file(source_path: String, destination_path: String) -> Result<(), String> {
    ensure_parent_directory(&destination_path)?;
    std::fs::copy(&source_path, &destination_path)
        .map(|_| ())
        .map_err(|error| error.to_string())
}

#[tauri::command]
fn get_file_name(path: String) -> String {
    std::path::Path::new(&path)
        .file_name()
        .and_then(|n| n.to_str())
        .unwrap_or("Untitled")
        .to_string()
}

#[tauri::command]
fn allow_fs_scope_path<R: tauri::Runtime>(
    app: tauri::AppHandle<R>,
    path: String,
    directory: bool,
    recursive: bool,
) -> Result<(), String> {
    let trimmed = path.trim();
    if trimmed.is_empty() {
        return Err("Missing file system path".to_string());
    }

    let scope = app.fs_scope();
    let candidate = PathBuf::from(trimmed);

    if directory {
        scope
            .allow_directory(candidate, recursive)
            .map_err(|error| error.to_string())
    } else {
        scope
            .allow_file(candidate)
            .map_err(|error| error.to_string())
    }
}

#[tauri::command]
fn take_pending_open_paths(
    state: tauri::State<'_, PendingOpenPaths>,
) -> Result<Vec<String>, String> {
    let mut pending_paths = state
        .0
        .lock()
        .map_err(|_| "Failed to access pending open paths".to_string())?;
    Ok(std::mem::take(&mut *pending_paths))
}

#[tauri::command]
async fn fetch_remote_image_data_url(url: String) -> Result<String, String> {
    let parsed_url =
        reqwest::Url::parse(&url).map_err(|_| "Invalid remote image URL".to_string())?;
    match parsed_url.scheme() {
        "http" | "https" => {}
        _ => return Err("Only HTTP and HTTPS image URLs are supported".to_string()),
    }

    let client = reqwest::Client::builder()
        .redirect(reqwest::redirect::Policy::limited(5))
        .timeout(std::time::Duration::from_secs(15))
        .build()
        .map_err(|error| format!("Failed to initialize image loader: {error}"))?;

    let response = client
        .get(parsed_url.clone())
        .header(USER_AGENT, PREVIEW_IMAGE_USER_AGENT)
        .send()
        .await
        .map_err(|error| format!("Failed to fetch remote image: {error}"))?
        .error_for_status()
        .map_err(|error| format!("Remote image request failed: {error}"))?;

    if response
        .content_length()
        .is_some_and(|length| length > MAX_REMOTE_IMAGE_BYTES as u64)
    {
        return Err("Remote image is too large to preview safely".to_string());
    }

    let content_type = resolve_remote_image_content_type(
        response
            .headers()
            .get(CONTENT_TYPE)
            .and_then(|value| value.to_str().ok()),
        parsed_url.path(),
    )
    .ok_or_else(|| "Remote resource is not a supported image".to_string())?;

    let bytes = response
        .bytes()
        .await
        .map_err(|error| format!("Failed to read remote image data: {error}"))?;

    if bytes.len() > MAX_REMOTE_IMAGE_BYTES {
        return Err("Remote image is too large to preview safely".to_string());
    }

    Ok(format!(
        "data:{content_type};base64,{}",
        base64::engine::general_purpose::STANDARD.encode(bytes)
    ))
}

#[tauri::command]
fn fetch_local_image_data_url(
    source: String,
    document_path: Option<String>,
) -> Result<String, String> {
    let resolved_path = resolve_local_image_path(&source, document_path.as_deref())?;
    let bytes = std::fs::read(&resolved_path)
        .map_err(|error| format!("Failed to read local image: {error}"))?;

    if bytes.len() > MAX_LOCAL_IMAGE_BYTES {
        return Err("Local image is too large to preview safely".to_string());
    }

    let content_type = infer_image_content_type(&resolved_path.to_string_lossy())
        .ok_or_else(|| "Local resource is not a supported image".to_string())?;

    Ok(format!(
        "data:{content_type};base64,{}",
        base64::engine::general_purpose::STANDARD.encode(bytes)
    ))
}

fn resolve_remote_image_content_type(header_value: Option<&str>, path: &str) -> Option<String> {
    normalize_image_content_type(header_value)
        .map(str::to_string)
        .or_else(|| infer_image_content_type(path).map(str::to_string))
}

fn normalize_image_content_type(header_value: Option<&str>) -> Option<&str> {
    let mime = header_value?.split(';').next()?.trim();
    mime.starts_with("image/").then_some(mime)
}

fn infer_image_content_type(path: &str) -> Option<&'static str> {
    let extension = path
        .rsplit_once('.')
        .map(|(_, extension)| extension)
        .unwrap_or_default()
        .to_ascii_lowercase();

    match extension.as_str() {
        "png" => Some("image/png"),
        "jpg" | "jpeg" => Some("image/jpeg"),
        "gif" => Some("image/gif"),
        "webp" => Some("image/webp"),
        "bmp" => Some("image/bmp"),
        "svg" => Some("image/svg+xml"),
        "ico" => Some("image/x-icon"),
        "avif" => Some("image/avif"),
        _ => None,
    }
}

fn resolve_local_image_path(
    source: &str,
    document_path: Option<&str>,
) -> Result<std::path::PathBuf, String> {
    let trimmed_source = source.trim();
    if trimmed_source.is_empty() {
        return Err("Missing local image source".to_string());
    }

    if matches!(
        reqwest::Url::parse(trimmed_source).ok().map(|url| url.scheme().to_ascii_lowercase()),
        Some(scheme) if scheme == "http" || scheme == "https" || scheme == "data" || scheme == "blob"
    ) {
        return Err("Expected a local image source".to_string());
    }

    if trimmed_source.to_ascii_lowercase().starts_with("file:") {
        let url = reqwest::Url::parse(trimmed_source)
            .map_err(|error| format!("Invalid local image URL: {error}"))?;
        return url
            .to_file_path()
            .map_err(|_| "Unsupported local image file URL".to_string());
    }

    let candidate_path = std::path::Path::new(trimmed_source);
    if candidate_path.is_absolute() {
        return Ok(candidate_path.to_path_buf());
    }

    let Some(document_path) = document_path else {
        return Err("Relative local image source requires a document path".to_string());
    };
    let Some(parent_dir) = std::path::Path::new(document_path).parent() else {
        return Err("Could not resolve the current document directory".to_string());
    };

    Ok(parent_dir.join(candidate_path))
}

fn ensure_parent_directory(path: &str) -> Result<(), String> {
    let Some(parent) = std::path::Path::new(path).parent() else {
        return Ok(());
    };

    if parent.as_os_str().is_empty() {
        return Ok(());
    }

    std::fs::create_dir_all(parent).map_err(|error| error.to_string())
}

fn is_allowed_editor_navigation(url: &reqwest::Url) -> bool {
    match url.scheme() {
        "tauri" => is_editor_entry_path(url.path()),
        "http" | "https" => {
            is_editor_loopback_host(url.host_str()) && is_editor_entry_path(url.path())
        }
        _ => false,
    }
}

fn is_pdf_export_webview_label(label: &str) -> bool {
    label.starts_with(pdf_export::PDF_WEBVIEW_LABEL_PREFIX)
}

fn is_browser_webview_label(label: &str) -> bool {
    label.starts_with("browser-")
}

fn append_log(msg: &str) {
    if let Ok(mut file) = std::fs::OpenOptions::new()
        .create(true)
        .append(true)
        .open("E:\\workspace\\no.1-markdown-editor-v2\\debug_webview.log")
    {
        use std::io::Write;
        let _ = writeln!(
            file,
            "[{}] {}",
            chrono::Local::now().format("%H:%M:%S"),
            msg
        );
    }
}

#[tauri::command]
fn log_debug(msg: String) {
    append_log(&format!("[JS] {}", msg));
}

#[tauri::command]
async fn create_browser_webview<R: tauri::Runtime>(
    app: tauri::AppHandle<R>,
    label: String,
    url: String,
    x: f64,
    y: f64,
    width: f64,
    height: f64,
) -> Result<(), String> {
    append_log(&format!(
        "create_browser_webview: label={}, url={}, x={}, y={}, w={}, h={}",
        label, url, x, y, width, height
    ));
    let main_window = app
        .get_window("main")
        .ok_or_else(|| "Main window not found".to_string())?;

    if let Some(webview) = app.get_webview(&label) {
        append_log("webview already exists, repositioning and showing");
        let (tx, rx) = tokio::sync::oneshot::channel();
        let _ = app.run_on_main_thread(move || {
            let res = (|| -> Result<(), String> {
                let _ = webview.set_position(Position::Logical(LogicalPosition::new(x, y)));
                let _ = webview.set_size(Size::Logical(LogicalSize::new(width, height)));
                let _ = webview.show();
                let _ = webview.set_focus();
                Ok(())
            })();
            let _ = tx.send(res);
        });
        return rx.await.map_err(|e| format!("Channel error: {e}"))?;
    }

    append_log("creating new child webview");
    let webview_url = WebviewUrl::External(url.parse().map_err(|error| {
        let err_msg = format!("Invalid URL: {error}");
        append_log(&err_msg);
        err_msg
    })?);
    let label_clone = label.clone();
    let app_handle = app.clone();
    let app_handle_title = app.clone();
    let webview_builder = WebviewBuilder::new(&label, webview_url)
        .zoom_hotkeys_enabled(true)
        .initialization_script(BROWSER_BRIDGE_SCRIPT)
        .on_page_load(move |_webview, payload| {
            if let tauri::webview::PageLoadEvent::Finished = payload.event() {
                let url_str = payload.url().to_string();
                let _ = app_handle.emit(&format!("browser-url-changed-{}", label_clone), url_str);
            }
        })
        .on_document_title_changed(move |webview, title| {
            handle_browser_title_report(&app_handle_title, webview.label(), &title);
        });

    let (tx, rx) = tokio::sync::oneshot::channel();
    let _ = app.run_on_main_thread(move || {
        let res = (|| -> Result<(), String> {
            let child = main_window
                .add_child(
                    webview_builder,
                    LogicalPosition::new(x, y),
                    LogicalSize::new(width, height),
                )
                .map_err(|error| {
                    let err_msg = format!("Failed to create child webview: {error}");
                    append_log(&err_msg);
                    err_msg
                })?;

            let _ = child.show();
            let _ = child.set_focus();
            append_log("new child webview created and shown successfully");
            Ok(())
        })();
        let _ = tx.send(res);
    });

    rx.await.map_err(|e| format!("Channel error: {e}"))?
}

#[tauri::command]
async fn reposition_browser_webview<R: tauri::Runtime>(
    app: tauri::AppHandle<R>,
    label: String,
    x: f64,
    y: f64,
    width: f64,
    height: f64,
) -> Result<(), String> {
    if let Some(webview) = app.get_webview(&label) {
        let (tx, rx) = tokio::sync::oneshot::channel();
        let _ = app.run_on_main_thread(move || {
            let res = (|| -> Result<(), String> {
                webview
                    .set_position(Position::Logical(LogicalPosition::new(x, y)))
                    .map_err(|error| error.to_string())?;
                webview
                    .set_size(Size::Logical(LogicalSize::new(width, height)))
                    .map_err(|error| error.to_string())?;
                Ok(())
            })();
            let _ = tx.send(res);
        });
        rx.await.map_err(|e| format!("Channel error: {e}"))?
    } else {
        Ok(())
    }
}

#[tauri::command]
async fn show_browser_webview<R: tauri::Runtime>(
    app: tauri::AppHandle<R>,
    label: String,
    visible: bool,
) -> Result<(), String> {
    if let Some(webview) = app.get_webview(&label) {
        let (tx, rx) = tokio::sync::oneshot::channel();
        let _ = app.run_on_main_thread(move || {
            let res = (|| -> Result<(), String> {
                if visible {
                    webview.show().map_err(|error| error.to_string())?;
                    webview.set_focus().map_err(|error| error.to_string())?;
                } else {
                    webview.hide().map_err(|error| error.to_string())?;
                }
                Ok(())
            })();
            let _ = tx.send(res);
        });
        rx.await.map_err(|e| format!("Channel error: {e}"))?
    } else {
        Ok(())
    }
}

#[tauri::command]
async fn destroy_browser_webview<R: tauri::Runtime>(
    app: tauri::AppHandle<R>,
    label: String,
) -> Result<(), String> {
    if let Some(webview) = app.get_webview(&label) {
        let (tx, rx) = tokio::sync::oneshot::channel();
        let _ = app.run_on_main_thread(move || {
            let res = webview.close().map_err(|error| error.to_string());
            let _ = tx.send(res);
        });
        rx.await.map_err(|e| format!("Channel error: {e}"))?
    } else {
        Ok(())
    }
}

#[tauri::command]
async fn browser_go_back<R: tauri::Runtime>(
    app: tauri::AppHandle<R>,
    label: String,
) -> Result<(), String> {
    if let Some(webview) = app.get_webview(&label) {
        let (tx, rx) = tokio::sync::oneshot::channel();
        let _ = app.run_on_main_thread(move || {
            let res = webview
                .eval("window.history.back()")
                .map_err(|error| error.to_string());
            let _ = tx.send(res);
        });
        rx.await.map_err(|e| format!("Channel error: {e}"))?
    } else {
        Ok(())
    }
}

#[tauri::command]
async fn browser_go_forward<R: tauri::Runtime>(
    app: tauri::AppHandle<R>,
    label: String,
) -> Result<(), String> {
    if let Some(webview) = app.get_webview(&label) {
        let (tx, rx) = tokio::sync::oneshot::channel();
        let _ = app.run_on_main_thread(move || {
            let res = webview
                .eval("window.history.forward()")
                .map_err(|error| error.to_string());
            let _ = tx.send(res);
        });
        rx.await.map_err(|e| format!("Channel error: {e}"))?
    } else {
        Ok(())
    }
}

#[tauri::command]
async fn browser_reload<R: tauri::Runtime>(
    app: tauri::AppHandle<R>,
    label: String,
) -> Result<(), String> {
    if let Some(webview) = app.get_webview(&label) {
        let (tx, rx) = tokio::sync::oneshot::channel();
        let _ = app.run_on_main_thread(move || {
            let res = webview
                .eval("window.location.reload()")
                .map_err(|error| error.to_string());
            let _ = tx.send(res);
        });
        rx.await.map_err(|e| format!("Channel error: {e}"))?
    } else {
        Ok(())
    }
}

#[tauri::command]
async fn browser_navigate<R: tauri::Runtime>(
    app: tauri::AppHandle<R>,
    label: String,
    url: String,
) -> Result<(), String> {
    if let Some(webview) = app.get_webview(&label) {
        let parsed_url = url
            .parse()
            .map_err(|error| format!("Invalid URL: {error}"))?;
        let (tx, rx) = tokio::sync::oneshot::channel();
        let _ = app.run_on_main_thread(move || {
            let res = webview
                .navigate(parsed_url)
                .map_err(|error| error.to_string());
            let _ = tx.send(res);
        });
        rx.await.map_err(|e| format!("Channel error: {e}"))?
    } else {
        Ok(())
    }
}

#[tauri::command]
async fn browser_set_zoom<R: tauri::Runtime>(
    app: tauri::AppHandle<R>,
    label: String,
    zoom: f64,
) -> Result<(), String> {
    if let Some(webview) = app.get_webview(&label) {
        let (tx, rx) = tokio::sync::oneshot::channel();
        let _ = app.run_on_main_thread(move || {
            let res = webview.set_zoom(zoom).map_err(|error| error.to_string());
            let _ = tx.send(res);
        });
        rx.await.map_err(|e| format!("Channel error: {e}"))?
    } else {
        Ok(())
    }
}

#[cfg(target_os = "windows")]
#[tauri::command]
async fn capture_browser_webview<R: tauri::Runtime>(
    app: tauri::AppHandle<R>,
    label: String,
) -> Result<String, String> {
    use std::sync::mpsc;
    use windows::Win32::System::Com::IStream;
    use windows::Win32::UI::Shell::SHCreateMemStream;
    use webview2_com::Microsoft::Web::WebView2::Win32::COREWEBVIEW2_CAPTURE_PREVIEW_IMAGE_FORMAT_PNG;

    let webview = app.get_webview(&label).ok_or_else(|| "Webview not found".to_string())?;

    let (tx, rx) = mpsc::channel::<Result<String, String>>();

    webview.with_webview(move |platform_webview| {
        let setup_tx = tx.clone();
        let outcome = (|| -> Result<(), String> {
            let controller = platform_webview.controller();
            unsafe {
                let core = controller
                    .CoreWebView2()
                    .map_err(|error| format!("Failed to get CoreWebView2: {error}"))?;

                let stream: IStream = SHCreateMemStream(None)
                    .ok_or_else(|| "SHCreateMemStream failed".to_string())?;

                let handler_stream = stream.clone();
                let completion_tx = tx.clone();
                let handler = webview2_com::CapturePreviewCompletedHandler::create(Box::new(
                    move |error_code| {
                        let outcome = (|| -> Result<String, String> {
                            if !error_code.is_ok() {
                                return Err(format!("CapturePreview completed with error: {:?}", error_code));
                            }

                            handler_stream.Seek(0, windows::Win32::System::Com::STREAM_SEEK_SET, None)
                                .map_err(|e| format!("Seek failed: {e:?}"))?;

                            let mut buffer = Vec::new();
                            let mut chunk = [0u8; 4096];
                            loop {
                                let mut bytes_read: u32 = 0;
                                let hr = handler_stream.Read(chunk.as_mut_ptr() as *mut _, chunk.len() as u32, Some(&mut bytes_read as *mut u32));
                                if !hr.is_ok() {
                                    return Err(format!("Read failed with HRESULT {:?}", hr));
                                }
                                if bytes_read == 0 {
                                    break;
                                }
                                buffer.extend_from_slice(&chunk[..bytes_read as usize]);
                            }

                            let b64 = base64::engine::general_purpose::STANDARD.encode(&buffer);
                            Ok(format!("data:image/png;base64,{b64}"))
                        })();
                        let _ = completion_tx.send(outcome);
                        Ok(())
                    },
                ));

                core.CapturePreview(
                    COREWEBVIEW2_CAPTURE_PREVIEW_IMAGE_FORMAT_PNG,
                    &stream,
                    &handler,
                )
                .map_err(|error| format!("CapturePreview invocation failed: {error}"))?;
            }
            Ok(())
        })();

        if let Err(error) = outcome {
            let _ = setup_tx.send(Err(error));
        }
    })
    .map_err(|error| format!("with_webview dispatch failed: {error}"))?;

    let out = tokio::task::spawn_blocking(move || {
        rx.recv_timeout(std::time::Duration::from_secs(5))
            .map_err(|_| "CapturePreview timed out".to_string())
            .and_then(|result| result)
    })
    .await
    .map_err(|error| format!("CapturePreview task was cancelled: {error}"))?;
    out
}

#[cfg(not(target_os = "windows"))]
#[tauri::command]
async fn capture_browser_webview<R: tauri::Runtime>(
    _app: tauri::AppHandle<R>,
    _label: String,
) -> Result<String, String> {
    Err("capture_not_supported".to_string())
}


fn is_editor_loopback_host(host: Option<&str>) -> bool {
    host.is_some_and(|host| {
        matches!(host, "localhost" | "127.0.0.1" | "::1") || host.ends_with(".localhost")
    })
}

fn is_editor_entry_path(path: &str) -> bool {
    matches!(path, "" | "/" | "/index.html")
}

fn collect_launch_paths() -> Vec<String> {
    let current_dir = std::env::current_dir().ok();
    collect_launch_paths_from_args(std::env::args_os().skip(1), current_dir.as_deref())
}

fn collect_launch_paths_from_args<I>(args: I, cwd: Option<&Path>) -> Vec<String>
where
    I: IntoIterator,
    I::Item: Into<OsString>,
{
    let mut launch_paths = Vec::new();

    for arg in args {
        let arg = arg.into();
        let Some(path) = normalize_launch_arg(&arg, cwd) else {
            continue;
        };

        if !launch_paths.contains(&path) {
            launch_paths.push(path);
        }
    }

    launch_paths
}

fn normalize_launch_arg(arg: &OsStr, cwd: Option<&Path>) -> Option<String> {
    let raw = arg.to_string_lossy();
    if raw.is_empty() {
        return None;
    }

    let path = if raw.to_ascii_lowercase().starts_with("file:") {
        let url = reqwest::Url::parse(&raw).ok()?;
        let path = url.to_file_path().ok()?;
        if !path.is_file() {
            return None;
        }
        path
    } else {
        let candidate = PathBuf::from(arg);
        if candidate.is_file() {
            candidate
        } else if candidate.is_absolute() || raw.starts_with('-') {
            return None;
        } else {
            let resolved = cwd?.join(candidate);
            if !resolved.is_file() {
                return None;
            }
            resolved
        }
    };

    if !is_supported_launch_document_path(&path) {
        return None;
    }

    Some(path.to_string_lossy().into_owned())
}

fn is_supported_launch_document_path(path: &Path) -> bool {
    path.extension()
        .and_then(|extension| extension.to_str())
        .is_some_and(|extension| {
            matches!(
                extension.to_ascii_lowercase().as_str(),
                "md" | "markdown" | "mdx" | "txt"
            )
        })
}

fn focus_main_window<R: tauri::Runtime>(app: &tauri::AppHandle<R>) {
    let Some(window) = app.get_webview_window("main") else {
        return;
    };

    let _ = window.unminimize();
    let _ = window.show();
    let _ = window.set_focus();
}

#[cfg(any(target_os = "macos", windows, target_os = "linux"))]
fn register_single_instance_plugin(
    builder: tauri::Builder<tauri::Wry>,
) -> tauri::Builder<tauri::Wry> {
    builder.plugin(tauri_plugin_single_instance::init(|app, argv, cwd| {
        focus_main_window(app);

        let current_dir = PathBuf::from(&cwd);
        let launch_paths = collect_launch_paths_from_args(argv, Some(current_dir.as_path()));
        if launch_paths.is_empty() {
            return;
        }

        if let Some(window) = app.get_webview_window("main") {
            let _ = window.emit(SINGLE_INSTANCE_OPEN_FILES_EVENT, launch_paths);
        }
    }))
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    let pending_open_paths = PendingOpenPaths(Mutex::new(collect_launch_paths()));
    let ai_in_flight_requests =
        ai::AiInFlightRequests(Mutex::new(std::collections::HashMap::new()));
    let ai_oauth_token_cache = ai::AiOAuthTokenCache(Mutex::new(std::collections::HashMap::new()));
    let builder = tauri::Builder::default();

    #[cfg(any(target_os = "macos", windows, target_os = "linux"))]
    let builder = register_single_instance_plugin(builder);

    builder
        .manage(pending_open_paths)
        .manage(ai_in_flight_requests)
        .manage(ai_oauth_token_cache)
        .manage(BrowserTitleChannels::default())
        .plugin(
            tauri::plugin::Builder::<tauri::Wry>::new("editor-navigation-guard")
                .on_navigation(|webview, url| {
                    append_log(&format!(
                        "on_navigation: label={}, url={}",
                        webview.label(),
                        url
                    ));
                    if is_pdf_export_webview_label(webview.label()) {
                        // Hidden webviews created for silent PDF export are allowed to
                        // load the local `file://` source html we stage for them.
                        return true;
                    }
                    if is_browser_webview_label(webview.label()) {
                        append_log(&format!(
                            "allowing navigation for browser label: {}",
                            webview.label()
                        ));
                        return true;
                    }
                    let allowed = is_allowed_editor_navigation(url);
                    append_log(&format!("is_allowed_editor_navigation: {}", allowed));
                    allowed
                })
                .build(),
        )
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_fs::init())
        .plugin(tauri_plugin_opener::init())
        .invoke_handler(tauri::generate_handler![
            ai::ai_load_provider_state,
            ai::ai_save_provider_config,
            ai::ai_store_provider_api_key,
            ai::ai_clear_provider_api_key,
            ai::ai_store_oci_key_file_passphrase,
            ai::ai_clear_oci_key_file_passphrase,
            ai::ai_store_hosted_agent_client_secret,
            ai::ai_clear_hosted_agent_client_secret,
            ai::ai_run_completion,
            ai::ai_cancel_completion,
            ai::ai_list_enrichment_jobs,
            ai::ai_generate_enrichment_job,
            ai::ai_get_enrichment_job,
            image_hosting::image_hosting_load_state,
            image_hosting::image_hosting_save_config,
            image_hosting::image_hosting_store_pat,
            image_hosting::image_hosting_clear_pat,
            image_hosting::image_hosting_verify,
            image_hosting::image_hosting_upload,
            read_file,
            write_file,
            write_binary_file,
            copy_file,
            get_file_name,
            allow_fs_scope_path,
            take_pending_open_paths,
            fetch_remote_image_data_url,
            fetch_local_image_data_url,
            pdf_export::export_pdf_to_file,
            update::check_for_app_update,
            log_debug,
            create_browser_webview,
            reposition_browser_webview,
            show_browser_webview,
            destroy_browser_webview,
            browser_go_back,
            browser_go_forward,
            browser_reload,
            browser_navigate,
            browser_set_zoom,
            capture_browser_webview,
            browser_report_content,
            browser_collect_content
        ])
        .setup(|_app| {
            #[cfg(debug_assertions)]
            {
                let window = _app.get_webview_window("main").unwrap();
                window.open_devtools();
            }
            Ok(())
        })
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}

#[cfg(test)]
mod tests {
    use super::collect_launch_paths_from_args;
    use super::is_allowed_editor_navigation;
    use super::read_file;
    use std::ffi::OsString;
    use std::fs;
    use std::path::PathBuf;
    use std::time::{SystemTime, UNIX_EPOCH};

    fn make_temp_path(prefix: &str, extension: &str) -> PathBuf {
        let unique = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .expect("system clock before unix epoch")
            .as_nanos();

        std::env::temp_dir().join(format!(
            "no1-markdown-editor-{prefix}-{}-{unique}.{extension}",
            std::process::id(),
        ))
    }

    fn make_temp_markdown_path(prefix: &str) -> PathBuf {
        make_temp_path(prefix, "md")
    }

    #[test]
    fn read_file_returns_markdown_contents() {
        let existing_path = make_temp_markdown_path("async-read");
        fs::write(&existing_path, "# async read").expect("write temp markdown file");

        let content =
            tauri::async_runtime::block_on(read_file(existing_path.to_string_lossy().into_owned()))
                .expect("read temp markdown file");

        assert_eq!(content, "# async read");

        let _ = fs::remove_file(existing_path);
    }

    #[test]
    fn collect_launch_paths_ignores_flags_and_missing_files() {
        let existing_path = make_temp_markdown_path("launch");
        fs::write(&existing_path, "# launch").expect("write temp launch file");

        let args = vec![
            OsString::from("--flag"),
            existing_path.as_os_str().to_os_string(),
            OsString::from("missing-launch-file.md"),
        ];

        let launch_paths = collect_launch_paths_from_args(args, None);

        assert_eq!(
            launch_paths,
            vec![existing_path.to_string_lossy().into_owned()]
        );

        let _ = fs::remove_file(existing_path);
    }

    #[test]
    fn collect_launch_paths_ignores_unsupported_existing_files() {
        let executable_path = make_temp_path("app-argv0", "exe");
        let markdown_path = make_temp_markdown_path("single-instance-open");
        fs::write(&executable_path, "fake executable").expect("write temp executable path");
        fs::write(&markdown_path, "# opened document").expect("write temp markdown path");

        let args = vec![
            executable_path.as_os_str().to_os_string(),
            markdown_path.as_os_str().to_os_string(),
        ];

        let launch_paths = collect_launch_paths_from_args(args, None);

        assert_eq!(
            launch_paths,
            vec![markdown_path.to_string_lossy().into_owned()]
        );

        let _ = fs::remove_file(executable_path);
        let _ = fs::remove_file(markdown_path);
    }

    #[test]
    fn collect_launch_paths_supports_file_urls_and_deduplicates_entries() {
        let existing_path = make_temp_markdown_path("file-url");
        fs::write(&existing_path, "# file url").expect("write temp file url launch file");

        let file_url = reqwest::Url::from_file_path(&existing_path)
            .expect("convert temp launch path to file url")
            .to_string();

        let args = vec![
            existing_path.as_os_str().to_os_string(),
            OsString::from(file_url),
        ];

        let launch_paths = collect_launch_paths_from_args(args, None);

        assert_eq!(
            launch_paths,
            vec![existing_path.to_string_lossy().into_owned()]
        );

        let _ = fs::remove_file(existing_path);
    }

    #[test]
    fn collect_launch_paths_resolves_relative_paths_against_cwd() {
        let temp_dir = std::env::temp_dir().join(format!(
            "no1-markdown-editor-relative-{}-{}",
            std::process::id(),
            SystemTime::now()
                .duration_since(UNIX_EPOCH)
                .expect("system clock before unix epoch")
                .as_nanos()
        ));
        fs::create_dir_all(&temp_dir).expect("create temp directory");

        let existing_path = temp_dir.join("relative-launch.md");
        fs::write(&existing_path, "# relative launch").expect("write temp relative launch file");

        let args = vec![OsString::from("relative-launch.md")];
        let launch_paths = collect_launch_paths_from_args(args, Some(temp_dir.as_path()));

        assert_eq!(
            launch_paths,
            vec![existing_path.to_string_lossy().into_owned()]
        );

        let _ = fs::remove_file(existing_path);
        let _ = fs::remove_dir(temp_dir);
    }

    #[test]
    fn navigation_guard_allows_only_editor_entry_documents() {
        for url in [
            "tauri://localhost/",
            "tauri://localhost/index.html",
            "http://127.0.0.1:1420/",
            "https://tauri.localhost/index.html",
        ] {
            let parsed = reqwest::Url::parse(url).expect("parse allowed url");
            assert!(
                is_allowed_editor_navigation(&parsed),
                "expected to allow {url}"
            );
        }
    }

    #[test]
    fn navigation_guard_blocks_external_and_in_app_page_replacements() {
        for url in [
            "https://example.com/",
            "http://127.0.0.1:1420/guide.md",
            "http://localhost:1420/image.png",
            "file:///tmp/demo.md",
        ] {
            let parsed = reqwest::Url::parse(url).expect("parse blocked url");
            assert!(
                !is_allowed_editor_navigation(&parsed),
                "expected to block {url}"
            );
        }
    }
}
